### ISSUE TITLE
Building API reference fails

### ISSUE THREAD

**Issue by evelinag** [fsprojects/FSharp.Data.Toolbox#7]
with the following error:

```
Microsoft.FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange:  Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange' was thrown.
    at Microsoft.FSharp.Compiler.Tast.CcuThunk.EnsureDerefable(String[] requiring
Path) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\tast.fs:line 3035
at Microsoft.FSharp.Compiler.Tast.NonLocalEntityRef.TryDeref(Boolean canError) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\tast.fs:line 2452
at Microsoft.FSharp.Compiler.Tast.EntityRef.get_Deref() in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\tast.fs:line 2537
at Microsoft.FSharp.Compiler.Tastops.stripTyEqnsA(TcGlobals g, Boolean canShortcut, TType ty) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\tastops.fs:line 616
at Microsoft.FSharp.Compiler.Infos.GetSuperTypeOfType(TcGlobals g, ImportMapamap, range m, TType typ) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\infos.fs:line 49
```

**Comment by nhirschey** [comment]
Hi @evelinag , the build now works. Could you put the new packages on nuget.org?
